### ISSUE TITLE
Change when the Exit Sceen pops up

### ISSUE THREAD

**Issue by JNguyen96** [UCSB-CS56-Projects/cs56-games-beetle#17]
As of now, the exit screen pops up right after the button is pressed for the winning roll. This can cause confusing as the player does not always know who wins the round until they see the scoreboard. Fix it so that the winner of the game is displayed before the exit screen appears.
- 100 points

**Comment by hannavigil** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (100 pts)

**Comment by athielk** [comment]
it could also be put on exit screen
