### ISSUE TITLE
Save Player name when re-selecting level

### ISSUE THREAD

**Issue by JNguyen96** [UCSB-CS56-Projects/cs56-games-beetle#18]
Currently, when the player selects a new level at the exit screen, the window for choosing 1 or 2 Players followed by the window for entering your name always appear. Change it so that the player only has to input their name once and then save it for following games until the program is exited.
- 150 points

**Comment by hannavigil** [comment]
W16 OK

**Comment by athielk** [comment]
F16 OK (150 pts)
