### ISSUE TITLE
Add Beetle Images

### ISSUE THREAD

**Issue by bronhuston** [UCSB-CS56-Projects/cs56-games-beetle#3]
Depends #1 
Currently, the user is only told of the beetle being "formed".

Add graphics for the user and computers beetles that are formed throughout the game.

For example: If at the beginning of the game the user rolls the number for the body, an image for the body should appear and should remain to be built upon for the rest of the game.

~estimated 250

**Comment by athielk** [comment]
F16 OK (250 pts)
